package com.appactor.android.models

public data class AppActorEntitlementInfo(
    val identifier: String,
    val isActive: Boolean,
    val status: String? = null,
    val productIdentifier: String? = null,
    val grantedBy: String? = null,
    val ownershipType: AppActorOwnershipType = AppActorOwnershipType.Unknown,
    val periodType: AppActorPeriodType = AppActorPeriodType.Unknown,
    val willRenew: Boolean = false,
    val subscriptionStatus: AppActorSubscriptionStatus? = null,
    val store: AppActorStore = AppActorStore.Unknown,
    val basePlanId: String? = null,
    val offerId: String? = null,
    val isSandbox: Boolean? = null,
    val cancellationReason: AppActorCancellationReason? = null,
    val purchaseDate: String? = null,
    val startsAt: String? = null,
    val latestPurchaseDate: String? = null,
    val originalPurchaseDate: String? = null,
    val expirationDate: String? = null,
    val gracePeriodExpiresAt: String? = null,
    val billingIssueDetectedAt: String? = null,
    val unsubscribeDetectedAt: String? = null,
    val renewedAt: String? = null,
    val activePromotionalOfferType: String? = null,
    val activePromotionalOfferId: String? = null,
)
